services:
  backend:
    image: rajdeep03/fluent-backend:latest
    container_name: fluent-backend
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5000:5000"

  frontend:
    image: rajdeep03/fluent-frontend:latest
    container_name: fluent-frontend
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "80:80"